version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sightseeing_board
      TZ: "Asia/Tokyo"
    volumes:
      - ../sightseeing-board-db:/var/lib/postgresql/data